default: &default
  adapter: postgresql
  encoding: unicode
  host: database
  port: 5432
  user: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: inventory_assignment_development

test:
  <<: *default
  database: inventory_assignment_test

production:
  <<: *default
  database: inventory_assignment_production
  username: inventory_assignment
  password: <%= ENV['INVENTORY_ASSIGNMENT_DATABASE_PASSWORD'] %>
